services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: video_db
    volumes:
      - ./mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    ports:
      - "5000:5000"
    build: 
      context: ./auth-service
      dockerfile: ../Dockerfile
      args:
        SERVICE_NAME: auth-service
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  file-service:
    build: 
      context: ./file-service
      dockerfile: ../Dockerfile
      args:
        SERVICE_NAME: file-service
    volumes:
      - video_data:/storage

  upload-service:
    build: 
      context: ./upload-service
      dockerfile: ../Dockerfile
      args:
        SERVICE_NAME: upload-service
    ports: ["5003:5003"]
    environment:
      - DB_DSN=root:${DB_ROOT_PASSWORD}@tcp(mysql-db:3306)/video_db
    depends_on: [auth-service, file-service, mysql-db]

  streaming-service:
    build: 
      context: ./streaming-service
      dockerfile: ../Dockerfile
      args:
        SERVICE_NAME: streaming-service
    ports: ["5002:5002"]
    environment:
      - DB_DSN=root:${DB_ROOT_PASSWORD}@tcp(mysql-db:3306)/video_db
    volumes:
      - video_data:/storage
    depends_on: [auth-service, mysql-db]
  
  upload-app:
    build:
      context: ./upload-app
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - upload-service

  streaming-app:
    build:
      context: ./streaming-app
    ports:
      - "3001:80"
    depends_on:
      - streaming-service



volumes:
  video_data:
